### ISSUE TITLE
Feature Request Docker container 

### ISSUE THREAD

**Issue by dailypush** [bertvandepoel/tabby#21]
As a home user it would be great to have this in a docker container for quick deployment, demoing and testing. 

Stretch goal to run on  raspberry pi as an arm image

**Comment by bertvandepoel** [comment]
I have the skills, knowledge nor interest to maintain a docker image, so it's not something I will be adding. Personally, I just install Apache or Nginx with PHP and then install all the applications in there. I have no idea how you would even deal with the way database upgrades work in Tabby inside a docker context. I also think running a webserver and database server for each webapplication is a bit wasteful when it comes to resources, especially if you're using a Raspberry Pi. But I'm aware it's a popular choice.

However, there are Tabby users who have looked into this, for example in #13. I'm not sure if @the-alpaka is going to continue to maintain https://github.com/the-alpaka/docker_tabby and whether it works well. If it does, I'm certainly willing to mention it in the Tabby README. But then I'd like for a few people to get confirmation it works, and it would also be nice to know whether the image will be maintained or not (I should probably do another release soon, when I have the time, with some minor security fixes). Could you try out that docker image perhaps?

**Comment by the-alpaka** [comment]
Hey @bertvandepoel I'd be happy to maintain the container for this, that being said it still has work that's needed to be done. I haven't been able to successfully connect the database to it, I have a few ideas on what the problem may be and possible solutions. But I don't currently have to time to fix them as I'm super busy with school currently. I hope to have it fully working by the end of May but can't make any promises. Once it's fixed I will be sure to notify you, and hopefully a few others will be able to test it out for me.

**Comment by bertvandepoel** [comment]
No pressure at all! I just happened to be aware of your image :)

If you need any help or insight that's more about the code or the sysadmin side, then let me know. I know very little about the docker side of things, so there I can't offer much.

I'm sure that you'll be able to find some testers here and in issue 13 whenever you find the time!

**Comment by the-alpaka** [comment]
Hey so I found time to fix the container, I had issues getting .htaccess to work but it seems to be functioning correctly now. I moved everything over to a new repository [parksauce/tabby](https://github.com/parksauce/tabby) and will be maintaining it under a different github account @realjoshparker. I have to rewrite the documentation and hopefully I'll be able to get everything all situated by the end of day tomorrow. More extensive testing of the container is definitely still needed I haven't confirmed whether or not everything functions properly yet.

For anyone interested in testing the container can be pulled from the docker registry with `docker pull parksauce/tabby`. Below is an example of a compose file. Just be sure to use `tabby-db` as the hostname for connecting the database.

```yaml
version: '3'
services:

  tabby:
    image: parksauce/tabby
    container_name: tabby
    ports:
      - 8010:80
    volumes:
      - ./config:/config
    restart: unless-stopped

  db:
    image: linuxserver/mariadb
    container_name: tabby-db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=tabby
      - TZ=America/New_York
      - MYSQL_DATABASE=tabby
      - MYSQL_USER=tabby
      - MYSQL_PASSWORD=tabby
    volumes:
      - ./db:/config
    restart: unless-stopped
```
